// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MlKombin
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"upperCategory")]
            public string UpperCategory { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"upperColor")]
            public string UpperColor { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"bottomCategory")]
            public string BottomCategory { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"bottomColor")]
            public string BottomColor { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"shoesCategory")]
            public string ShoesCategory { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"shoesColor")]
            public string ShoesColor { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"season")]
            public string Season { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"temperature")]
            public float Temperature { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"isGoodCombo")]
            public bool IsGoodCombo { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"upperCategory")]
            public float[] UpperCategory { get; set; }

            [ColumnName(@"upperColor")]
            public float[] UpperColor { get; set; }

            [ColumnName(@"bottomCategory")]
            public float[] BottomCategory { get; set; }

            [ColumnName(@"bottomColor")]
            public float[] BottomColor { get; set; }

            [ColumnName(@"shoesCategory")]
            public float[] ShoesCategory { get; set; }

            [ColumnName(@"shoesColor")]
            public float[] ShoesColor { get; set; }

            [ColumnName(@"season")]
            public float[] Season { get; set; }

            [ColumnName(@"temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"isGoodCombo")]
            public bool IsGoodCombo { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public bool PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Probability")]
            public float Probability { get; set; }

        }

        #endregion

        private static string MLNetModelPath = "yeni_model.mlnet";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
